var tags = [
  {
    'name':'album', 
    'tags':[
      'Louis Armstrong  Hot Fives & Sevens full album',
      'Cannonball Adderley  Somethin’ Else full album',
      'Count Basie  Basie Straight Ahead full album',
      'Chet Baker  It Could Happen To You full album',
      'Chick Corea  My Spanish Heart full album',
      'Chick Corea  Return to Forever full album',
      'Art Blakey  Moanin’ full album',
      'Art Blakey  A Night at Birdland full album',
      'Art Blakey  Art Blakey\'s Jazz Messengers with Thelonious Monk full album',
      'Clifford Brown and Max Roach  At Basin Street full album',
      'John Coltrane  Blue Trane full album',
      'John Coltrane  My Favorite Things full album',
      'John Coltrane  Crescent full album',
      'John Coltrane  A Love Supreme full album',
      'John Coltrane and Johnny Hartman full album',
      'John McLaughlin Paco DeLucia Al DiMeola  Friday Night in San Francisco full ablum',
      'Miles Davis  Cookin’ full album',
      'Miles Davis  Kind of Blue full album',
      'Miles Davis  Complete Concert 1964 full album',
      'Duke Ellington  Ellington Uptown full album',
      'Duke Ellington  Far East Suite full album',
      'Bill Evans  Everybody Digs Bill Evans full album',
      'Bill Evans  Sunday at the Village Vanguard full album',
      'Bill Evans  Waltz For Debby full album',
      'Bill Evans  Explorations full album',
      'Bill Evans  Conversations With Myself full album',
      'Bill Evans and Jim Hall  Undercurrent full album',
      'Ella Fitzgerald  Ella in Berlin full album',
      'Ella Fitzgerald  Ella and Louis full album',
      'Dizzy Gillespie/Sonny Rollins/Sonny Stitt  Sunny Side Up full album',
      'Dexter Gordon  Homecoming full album',
      'Dexter Gordon  Go! full album',
      'Herbie Hancock  Maiden Voyage full album',
      'Herbie Hancock  Empyrean Isles full album',
      'Herbie Hancock  Headhunters full album',
      'Joe Henderson  Page One full album',
      'Billie Holiday  Lady in Satin full album',
      'Freddie Hubbard  Hub-Tones full album',
      'J.J. Johnson  Blue Trombone full album',
      'Lee Konitz  Motion full album',
      'Charles Mingus  Mingus Ah Um full album',
      'Thelonius Monk  Monk’s Dream full album',
      'Lee Morgan  Cornbread full album',
      'Lee Morgan  The Sidewinder full album'
      'Charlie Parker and Dizzy Gillespie  Bird and Diz full album',
      'Charlie Parker  The Complete Charlie Parker on Dial full album',
      'Chalier Parker With Strings',
      'Charles Mingus  Mingus Ah Um full album',
      'Charles Mingus  The Clown full album',
      'Oscar Peterson  Night Train full album',
      'Sonny Rollins  Saxophone Colossus full album',
      'Sonny Rollins  A Night at the Village Vanguard full album',
      'Horace Silver  Song For My Father full album',
      'Wayne Shorter  Speak No Evil full album',
      'Art Tatum  Solo Piano full album',
      'McCoy Tyner  The Real McCoy full album',
      'Sarah Vaughan  Sarah Vaughan full album',
      'Lester Young  Lester Young Trio full album',
      'Larry Young  Unity full album',
      'Nancy Wilson and Cannonball Adderley',
      'Bobby McFerrin  The Voice full album',
      'Charlie Haden and Pat Metheny  Beyond the Missouri Sky full album',
      'Dave Brubeck  Time Out full album',
      'Eric Dolphy  Out to Lunch! full album',
      'Grant Green  Idle Moments full album',
      'Hank Mobley  Soul Station full album',
      'Jimmy Smith and Wes Montgomery  Dynamic Duo full album',
      'Joe Pass  Intercontinental full album',
      'Keith Jarrett  La Scala full album',
      'Keith Jarrett  Tokyo solo full album',
      'Pat Metheny  Bright Size Life full album',
      'Pat Metheny  Imaginary day full album',
      'Pat Metheny  Secret Story full album',
      'Pat Metheny  The way up full album',
      'Pat Metheny  Watercolors full album',
      'Stan Getz and Charlie Byrd  Jazz Samba full album',
      'Stan Getz and Joao Gilberto  Getz/Gilberto full album',
      'Wayne Shorter  Speak No Evil full album',
      'Weather Report  Heavy Weather full album',
      'Wes Montgomery  Full House full album',
      'Wes Montgomery  The Incredible Jazz Guitar full album',
      'Yusef Lateef  Eastern Sounds full album'
    ]
  }
]

