var tags = [
  {
    'name':'album', 
    'tags':[
      'Louis Armstrong  Hot Fives & Sevens full album',
      'Cannonball Adderley  Somethin’ Else full album',
      'Count Basie  Basie Straight Ahead full album',
      'Chet Baker  It Could Happen To You full album',
      'Art Blakey  Moanin’ full album',
      'Art Blakey  A Night at Birdland full album',
      'Clifford Brown and Max Roach  At Basin Street full album',
      'John Coltrane  Blue Trane full album',
      'John Coltrane  My Favorite Things full album',
      'John Coltrane  Crescent full album',
      'Miles Davis  Cookin’ full album',
      'Miles Davis  Kind of Blue full album',
      'Miles Davis  Complete Concert 1964 full album',
      'Duke Ellington  Ellington Uptown full album',
      'Duke Ellington  Far East Suite full album',
      'Bill Evans  Everybody Digs Bill Evans full album',
      'Bill Evans  Sunday at the Village Vanguard full album',
      'Ella Fitzgerald  Ella in Berlin full album',
      'Ella Fitzgerald  Ella and Louis full album',
      'Dizzy Gillespie/Sonny Rollins/Sonny Stitt  Sunny Side Up full album',
      'Dexter Gordon  Homecoming full album',
      'Herbie Hancock  Maiden Voyage full album',
      'Herbie Hancock  Empyrean Isles full album',
      'Herbie Hancock  Headhunters full album',
      'Joe Henderson  Page One full album',
      'Billie Holiday  Lady in Satin full album',
      'Freddie Hubbard  Hub-Tones full album',
      'J.J. Johnson  Blue Trombone full album',
      'Lee Konitz  Motion full album',
      'Charles Mingus  Mingus Ah Um full album',
      'Thelonius Monk  Monk’s Dream full album',
      'Lee Morgan  Cornbread full album',
      'Charlie Parker and Dizzy Gillespie  Bird and Diz full album',
      'Charlie Parker  The Complete Charlie Parker on Dial full album',
      'Chalier Parker With Strings',
      'Oscar Peterson  Night Train full album',
      'Sonny Rollins  Saxophone Colossus full album',
      'Sonny Rollins  A Night at the Village Vanguard full album',
      'Horace Silver  Song For My Father full album',
      'Wayne Shorter  Speak No Evil full album',
      'Art Tatum  Solo Piano full album',
      'McCoy Tyner  The Real McCoy full album',
      'Sarah Vaughan  Sarah Vaughan full album',
      'Lester Young  Lester Young Trio full album',
      'Larry Young  Unity full album',
      'Nancy Wilson and Cannonball Adderley'
    ]
  }
]

