tags['opera'] = [
  {
  'name':'titles',
  'tags':[
    //1600–1699

    "L'Orfeo (Claudio Monteverdi)",
    "Il ritorno d'Ulisse in patria (Monteverdi)",
    "L'incoronazione di Poppea (Monteverdi)",
    "Ormindo (Francesco Cavalli)",
    "Giasone (Cavalli)",
    "La Calisto (Cavalli)",
    "Dido and Aeneas (Henry Purcell)",
    "The Fairy-Queen (Purcell)",
    //1700–1749",

    "Agrippina (Handel)",
    "Rinaldo (Handel)",
    "Giulio Cesare (Handel)",
    "Tamerlano (Handel)",
    "Rodelinda (Handel)",
    "The Beggar's Opera (Johann Christoph Pepusch)",
    "Acis and Galatea (Handel)",
    "Orlando (Handel)",
    "La serva padrona (Giovanni Battista Pergolesi)",
    "Hippolyte et Aricie (Jean-Philippe Rameau)",
    "Ariodante (Handel)",
    "Alcina (Handel)",
    "Les Indes galantes (Rameau)",
    "Castor et Pollux (Rameau)",
    "Serse (Handel)",
    "Semele (Handel)",
    "Platée (Rameau)",

    //1750–1799",

    "La buona figliuola (Niccolò Piccinni)",
    "Orfeo ed Euridice (Christoph Willibald Gluck)",
    "Alceste (Gluck)",
    "Bastien und Bastienne (Wolfgang Amadeus Mozart)",
    "Mitridate, re di Ponto (Mozart)",
    "Lucio Silla (Mozart)",
    "Iphigénie en Aulide (Gluck)",
    "La finta giardiniera (Mozart)",
    "Il re pastore (Mozart)",
    "Il mondo della luna (Joseph Haydn)",
    "Armide (Gluck)",
    "Iphigénie en Tauride (Gluck)",
    "Idomeneo (Mozart)",
    "Die Entführung aus dem Serail (Mozart)",
    "Il barbiere di Siviglia (Giovanni Paisiello)",
    "Der Schauspieldirektor (Mozart)",
    "Le nozze di Figaro (Mozart)",
    "Don Giovanni (Mozart)",
    "Così fan tutte (Mozart)",
    "La clemenza di Tito (Mozart)",
    "Die Zauberflöte (Mozart)",
    "Il matrimonio segreto (Domenico Cimarosa)",
    "Médée (Luigi Cherubini)",

    //1800–1832",

    "Fidelio (Ludwig van Beethoven)",
    "La vestale (Gaspare Spontini)",
    "La scala di seta (Gioachino Rossini)",
    "L'italiana in Algeri (Rossini)",
    "Tancredi (Rossini)",
    "Il turco in Italia (Rossini)",
    "Il barbiere di Siviglia (Rossini)",
    "Otello (Rossini)",
    "La Cenerentola (Rossini)",
    "La gazza ladra (Rossini)",
    "Mosè in Egitto (Rossini)",
    "La donna del lago (Rossini)",
    "Der Freischütz (Carl Maria von Weber)",
    "Euryanthe (von Weber)",
    "Semiramide (Rossini)",
    "La dame blanche (François-Adrien Boieldieu)",
    "Le siège de Corinthe (Rossini)",
    "Oberon (von Weber)",
    "Il pirata (Vincenzo Bellini)",
    "Der Vampyr (Heinrich Marschner)",
    "Le comte Ory (Rossini)",
    "La straniera (Bellini)",
    "William Tell (Rossini)",
    "Anna Bolena (Gaetano Donizetti)",
    "Fra Diavolo (Daniel Auber)",
    "I Capuleti e i Montecchi (Bellini)",
    "La sonnambula (Bellini)",
    "Norma (Bellini)",
    "Robert le diable (Giacomo Meyerbeer)",
    "L'elisir d'amore (Donizetti)",

    //1833–1849",

    "Beatrice di Tenda (Vincenzo Bellini)",
    "Hans Heiling (Heinrich Marschner)",
    "Lucrezia Borgia (Gaetano Donizetti)",
    "Maria Stuarda (Donizetti)",
    "Das Liebesverbot (Richard Wagner)",
    "I puritani (Bellini)",
    "La Juive (Fromental Halévy)",
    "Lucia di Lammermoor (Donizetti)",
    "A Life for the Tsar (Mikhail Glinka)",
    "Les Huguenots (Giacomo Meyerbeer)",
    "Roberto Devereux (Donizetti)",
    "Benvenuto Cellini (Hector Berlioz)",
    "Oberto (Giuseppe Verdi)",
    "La favorite (Donizetti)",
    "La fille du régiment (Donizetti)",
    "Un giorno di regno (Verdi)",
    "Der Wildschütz (Albert Lortzing)",
    "Nabucco (Verdi)",
    "Rienzi (Wagner)",
    "Ruslan and Lyudmila (Glinka)",
    "The Flying Dutchman (Wagner)",
    "Don Pasquale (Donizetti)",
    "I Lombardi alla prima crociata (Verdi)",
    "The Bohemian Girl (Michael Balfe)",
    "Ernani (Verdi)",
    "Tannhäuser (Wagner)",
    "Attila (Verdi)",
    "The Damnation of Faust (Berlioz)",
    "Macbeth (Verdi)",
    "Martha (Friedrich von Flotow)",
    "The Merry Wives of Windsor (Otto Nicolai)",
    "Le prophète (Meyerbeer)",
    "Luisa Miller (Verdi)",

    //1850–1875",

    "Genoveva (Robert Schumann)",
    "Lohengrin (Richard Wagner)",
    "Stiffelio (Giuseppe Verdi)",
    "Rigoletto (Verdi)",
    "Il trovatore (Verdi)",
    "La traviata (Verdi)",
    "Les vêpres siciliennes (Verdi)",
    "Der Barbier von Bagdad (Peter Cornelius)",
    "Orpheus in the Underworld (Jacques Offenbach)",
    "Les Troyens (Hector Berlioz)",
    "Faust (Charles Gounod)",
    "Un ballo in maschera (Verdi)",
    "Béatrice et Bénédict (Berlioz)",
    "La forza del destino (Verdi)",
    "Les pêcheurs de perles (Georges Bizet)",
    "La belle Hélène (Offenbach)",
    "Mireille (Gounod)",
    "L'Africaine (Giacomo Meyerbeer)",
    "Tristan und Isolde (Wagner)",
    "Mignon (Ambroise Thomas)",
    "The Bartered Bride (Bedřich Smetana)",
    "Don Carlos (Verdi)",
    "La jolie fille de Perth (Bizet)",
    "Roméo et Juliette (Gounod)",
    "Dalibor (Smetana)",
    "Die Meistersinger von Nürnberg (Wagner)",
    "Hamlet (Thomas)",
    "La Périchole (Offenbach)",
    "Mefistofele (Arrigo Boito)",
    "Das Rheingold (Wagner)",
    "Die Walküre (Wagner)",
    "Aida (Verdi)",
    "Boris Godunov (Modest Mussorgsky)",
    "Die Fledermaus (Johann Strauss II)",
    "The Two Widows (Smetana)",
    "Carmen (Bizet)",

    //1876–1899",

    "Siegfried (Richard Wagner)",
    "Götterdämmerung (Wagner)",
    "La Gioconda (Amilcare Ponchielli)",
    "L'étoile (Emmanuel Chabrier)",
    "Samson and Delilah (Camille Saint-Saëns)",
    "Eugene Onegin (Pyotr Ilyich Tchaikovsky)",
    "Hérodiade (Jules Massenet)",
    "Les contes d'Hoffmann (Jacques Offenbach)",
    "Simon Boccanegra (Giuseppe Verdi)",
    "Parsifal (Wagner)",
    "The Snow Maiden (Nikolai Rimsky-Korsakov)",
    "Lakmé (Léo Delibes)",
    "Le Villi (Puccini)",
    "Manon (Massenet)",
    "The Gypsy Baron (Johann Strauss II)",
    "Khovanshchina (Modest Mussorgsky)",
    "Le roi malgré lui (Chabrier)",
    "Otello (Verdi)",
    "Le roi d'Ys (Édouard Lalo)",
    "Cavalleria rusticana (Pietro Mascagni)",
    "Prince Igor (Alexander Borodin)",
    "The Queen of Spades (Tchaikovsky)",
    "L'amico Fritz (Mascagni)",
    "Iolanta (Tchaikovsky)",
    "La Wally (Alfredo Catalani)",
    "Pagliacci (Ruggiero Leoncavallo)",
    "Werther (Massenet)",
    "Falstaff (Verdi)",
    "Hänsel und Gretel (Engelbert Humperdinck)",
    "Manon Lescaut (Giacomo Puccini)",
    "Thaïs (Massenet)",
    "Andrea Chénier (Umberto Giordano)",
    "La bohème (Puccini)",
    "Königskinder (Humperdinck)",
    "Fedora (Giordano)",
    "Sadko (Rimsky-Korsakov)",
    "Cendrillon (Massenet)",
    "The Devil and Kate (Antonín Dvořák)",

    //1900–1920",

    "Louise (Gustave Charpentier)",
    "Tosca (Giacomo Puccini)",
    "Rusalka (Antonín Dvořák)",
    "Adriana Lecouvreur (Francesco Cilea)",
    "Pelléas et Mélisande (Claude Debussy)",
    "Saul og David (Carl Nielsen)",
    "Jenůfa (Leoš Janáček)",
    "Madama Butterfly (Puccini)",
    "The Merry Widow (Franz Lehár)",
    "Salome (Richard Strauss)",
    "Maskarade (Nielsen)",
    "A Village Romeo and Juliet (Frederick Delius)",
    "Ariane et Barbe-bleue (Paul Dukas)",
    "The Legend of the Invisible City of Kitezh and the Maiden Fevroniya (Nikolai Rimsky-Korsakov)",
    "Destiny (Janáček)",
    "Elektra (Strauss)",
    "Il segreto di Susanna (Ermanno Wolf-Ferrari)",
    "The Golden Cockerel (Rimsky-Korsakov)",
    "Don Quichotte (Jules Massenet)",
    "La fanciulla del West (Puccini)",
    "Der Rosenkavalier (Strauss)",
    "L'heure espagnole (Maurice Ravel)",
    "Ariadne auf Naxos (Strauss)",
    "Der ferne Klang (Franz Schreker)",
    "La vida breve (Manuel de Falla)",
    "The Immortal Hour (Rutland Boughton)",
    "The Nightingale (Igor Stravinsky)",
    "Savitri (Gustav Holst)",
    "Arlecchino (Ferruccio Busoni)",
    "Eine florentinische Tragödie (Alexander von Zemlinsky)",
    "La rondine (Puccini)",
    "Palestrina (Hans Pfitzner)",
    "Bluebeard's Castle (Béla Bartók)",
    "Gianni Schicchi (Puccini)",
    "Il tabarro (Puccini)",
    "Suor Angelica (Puccini)",
    "Die Frau ohne Schatten (Strauss)",
    "Die tote Stadt (Erich Wolfgang Korngold)",
    "The Excursions of Mr",

    //1921–1944",

    "Káťa Kabanová (Leoš Janáček)",
    "The Love for Three Oranges (Sergei Prokofiev)",
    "Der Zwerg (Alexander von Zemlinsky)",
    "Erwartung (Arnold Schoenberg)",
    "Hugh the Drover (Ralph Vaughan Williams)",
    "Intermezzo (Richard Strauss)",
    "The Cunning Little Vixen (Janáček)",
    "Doktor Faust (Ferruccio Busoni)",
    "L'enfant et les sortilèges (Maurice Ravel)",
    "Wozzeck (Alban Berg)",
    "Cardillac (Paul Hindemith)",
    "Háry János (Zoltán Kodály)",
    "King Roger (Karol Szymanowski)",
    "The Makropulos Affair (Janáček)",
    "Turandot (Giacomo Puccini)",
    "Oedipus Rex (Igor Stravinsky)",
    "Jonny spielt auf (Ernst Krenek)",
    "The Threepenny Opera (Kurt Weill)",
    "The Nose (Dmitri Shostakovich)",
    "Rise and Fall of the City of Mahagonny (Weill)",
    "From the House of the Dead (Janáček)",
    "Moses und Aron (Schoenberg)",
    "Arabella (Strauss)",
    "Lady Macbeth of the Mtsensk District (Shostakovich)",
    "Die schweigsame Frau (Strauss)",
    "Porgy and Bess (George Gershwin)",
    "Lulu (Berg)",
    "Riders to the Sea (Vaughan Williams)",
    "Daphne (Strauss)",
    "Julietta (Bohuslav Martinů)",
    "Mathis der Maler (Hindemith)",
    "Paul Bunyan (Benjamin Britten)",
    "Capriccio (Strauss)",
    "Der Kaiser von Atlantis (Viktor Ullmann)",

    //From 1945",

    "Peter Grimes (Benjamin Britten)",
    "War and Peace (Sergei Prokofiev)",
    "Betrothal in a Monastery (Prokofiev)",
    "The Medium (Gian Carlo Menotti)",
    "The Rape of Lucretia (Britten)",
    "Albert Herring (Britten)",
    "Dantons Tod (Gottfried von Einem)",
    "Les mamelles de Tirésias (Francis Poulenc)",
    "The Telephone, or L'Amour à trois (Menotti)",
    "Il prigioniero (Luigi Dallapiccola)",
    "The Consul (Menotti)",
    "Amahl and the Night Visitors (Menotti)",
    "Billy Budd (Britten)",
    "The Pilgrim's Progress (Ralph Vaughan Williams)",
    "The Rake's Progress (Igor Stravinsky)",
    "Boulevard Solitude (Hans Werner Henze)",
    "Gloriana (Britten)",
    "The Fiery Angel (Prokofiev)",
    "The Turn of the Screw (Britten)",
    "Troilus and Cressida (William Walton)",
    "The Midsummer Marriage (Michael Tippett)",
    "Candide (Leonard Bernstein)",
    "Dialogues of the Carmelites (Poulenc)",
    "Vanessa (Samuel Barber)",
    "La voix humaine (Poulenc)",
    "A Midsummer Night's Dream (Britten)",
    "Elegy for Young Lovers (Henze)",
    "King Priam (Tippett)",
    "Curlew River (Britten)",
    "Der junge Lord (Henze)",
    "Die Soldaten (Bernd Alois Zimmermann)",
    "Antony and Cleopatra (Barber)",
    "The Bassarids (Henze)",
    "The Bear (Walton)",
    "Punch and Judy (Harrison Birtwistle)",
    "The Prodigal Son (Britten)",
    "The Devils of Loudun (Krzysztof Penderecki)",
    "The Knot Garden (Tippett)",
    "Owen Wingrave (Britten)",
    "Taverner (Peter Maxwell Davies)",
    "Death in Venice (Britten)",
    "Le Grand Macabre (György Ligeti)",
    "Lear (Aribert Reimann)",
    "The Lighthouse (Davies)",
    "Saint François d'Assise (Olivier Messiaen)",
    "Un re in ascolto (Luciano Berio)",
    "Akhnaten (Philip Glass)",
    "The Mask of Orpheus (Birtwistle)",
    "A Night at the Chinese Opera (Judith Weir)",
    "Nixon in China (John Adams)",
    "Gawain (Birtwistle)"

  ]
}
]
